// app/layout.js
import { Montserrat, Roboto_Mono } from "next/font/google";
import "./globals.css";

// CSS variable for Montserrat
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "700"],
});

// CSS variable for Roboto Mono
const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${robotoMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
